export type LanguageCode = 'en' | 'de' | 'fr' | 'it' | 'es' | 'ko' | 'zh'

type MessageKey = keyof typeof messages.en

const storageKey = 'zenstudy-ui-language'

const languageNames: Record<LanguageCode, string> = {
  en: 'English',
  de: 'Deutsch',
  fr: 'Francais',
  it: 'Italiano',
  es: 'Espanol',
  ko: '한국어',
  zh: '中文'
}

const languageFlagIcons: Record<LanguageCode, string> = {
  en: 'twemoji:flag-united-kingdom',
  de: 'twemoji:flag-germany',
  fr: 'twemoji:flag-france',
  it: 'twemoji:flag-italy',
  es: 'twemoji:flag-spain',
  ko: 'twemoji:flag-south-korea',
  zh: 'twemoji:flag-china'
}

const messages = {
  en: {
    navDashboard: 'Dashboard', navVocabulary: 'Vocabulary', navFlashcards: 'Flashcards', navCharacters: 'Characters', navDialogue: 'Dialogue', navAdmin: 'Admin', navQuickAdd: 'Quick Add', navBackup: 'Backup', navStart: 'Start', navDays: 'days', navOpen: 'Open navigation', searchPlaceholder: 'Search words, readings, meanings...', searchLabel: 'Search study data', languageLabel: 'Language',
    loadingDatabase: 'Opening local study database...', databaseOpenError: 'SQLite database could not open', databaseWriteError: 'Check whether the Nuxt server can write to the project data folder.',
    dashEyebrow: 'Mastering Japanese', dashTitle: 'Welcome back.', dashCopy: 'A quiet study desk for vocabulary, kanji, and practical dialogue. Cards, hints, scenarios, and progress are stored in a local SQLite database.', dashBeginReview: 'Begin Review', metricVocabulary: 'Vocabulary', masteredWords: '{count} mastered words', metricDialogueSets: 'Dialogue Sets', scenarioPractice: 'Scenario-based practice', metricDailyGoal: 'Daily Goal', recentlyAdded: 'Recently Added', libraryNotes: 'Library Notes', viewLibrary: 'View Library', adminEyebrow: 'Administration', manageCorpus: 'Manage the study corpus', manageCorpusCopy: 'Vocabulary, personal hints, character cards, dialogue scenarios, tags, and examples are all editable from the styled admin area.', openAdmin: 'Open Admin', portableProgress: 'Portable Progress', exportImportTitle: 'Export or import SQLite data', exportImportCopy: 'Download a JSON backup and import it on another PC to keep content and review history moving with you.', backupTools: 'Backup Tools',
    vocabEyebrow: 'Personal Lexicon', vocabTitle: 'Vocabulary Library', vocabCopy: 'Search, review, and maintain the words that power flashcards and dialogue practice.', addWord: 'Add Word', noVocabularyMatches: 'No vocabulary matches your search.',
    flashEyebrow: 'Session Progress', flashTitle: 'Meaning Mode', flashCopy: 'Choose a session size, type the English meaning, and build a saved practice history with points.', newSession: 'New Session', howManyCards: 'How many cards?', cardsAvailable: '{count} vocabulary cards are available for review.', practiceFilters: 'Practice Filters', practiceTags: 'Practice Tags', allTagsSelected: 'All tags included', tagPoolCount: '{count} matching words', selectedTagCount: '{count} tags selected', selectTags: 'Select Tags', selectVocab: 'Select Vocab', selectAll: 'Select All', deselectAll: 'Deselect All', applySelection: 'Apply Selection', selectedVocabCount: '{count} selected', cardsThisSession: 'Cards this session', startFlashcards: 'Start Flashcards', practiceHistory: 'Practice History', recentSessions: 'Recent Sessions', noPracticeSessions: 'No practice sessions yet.', points: 'points', sessionComplete: 'Session Complete', correctCount: '{correct} / {total} correct', sessionScore: 'Your score was {score}%. This session was saved to practice history.', reviewVocabulary: 'Review Vocabulary', typeMeaningHint: 'Type the English meaning. Capitalization does not matter.', meaning: 'Meaning', checkAnswer: 'Check Answer', finishSession: 'Finish Session', nextCard: 'Next Card', context: 'Context', addVocabularyToBegin: 'Add vocabulary in Admin to begin a review session.', correct: 'Correct', incorrect: 'Incorrect', noPersonalHint: 'No personal hint saved yet.',
    charEyebrow: 'Character Practice', charTitle: 'Kanji Session', charCopy: 'Trace the character, use the low-opacity guide when needed, and pass with an 85% match.', readingMeaningHidden: 'Reading and meaning are hidden.', revealCharacter: 'Reveal Character', traceCharacter: 'Trace the character', drawCharacterCanvas: 'Character drawing canvas', showHint: 'Show Hint', hideHint: 'Hide Hint', clearDrawing: 'Clear', checkDrawing: 'Check Drawing', continuePractice: 'Continue', skipCharacter: 'Skip', drawingCorrect: 'Great job!', drawingTryAgain: 'Try again', drawingScore: 'Match score: {score}%', hard: 'Hard', good: 'Good', easy: 'Easy', addCharacterCards: 'Add character cards in Admin to begin.', strokesInfo: '{count} strokes. {hint}',
    dialogueEyebrow: 'Dialogue Trainer', dialogueTitle: 'Scenario Practice', dialogueCopy: 'Choose an existing dialogue, read the previous message, then answer with the best Japanese reply. Translations stay hidden until you check your response.', lines: 'lines', turn: 'Turn', replyMessage: 'Reply to the message', listen: 'Listen', hideHiragana: 'Hide Hiragana', showHiragana: 'Show Hiragana', hideTranslation: 'Hide Translation', showTranslation: 'Show Translation', tryThisReply: 'Try this reply', nextTurn: 'Next Turn', dialogueNeedsPrompt: 'This dialogue needs a non-learner prompt followed by a learner answer.', noDialogues: 'No dialogues yet.',
    manageDataTitle: 'Manage Study Data', manageDataCopy: 'Maintain vocabulary, hints, kanji cards, dialogue scenarios, and portable backups from one styled workspace.', tabVocabulary: 'vocabulary', tabCharacters: 'characters', tabDialogues: 'dialogues', tabBackup: 'backup', word: 'Word', reading: 'Reading', hint: 'Hint', character: 'Character', level: 'Level', strokes: 'Strokes', addCharacter: 'Add Character', delete: 'Delete', title: 'Title', setting: 'Setting', goal: 'Goal', linesJson: 'Lines JSON', addDialogue: 'Add Dialogue',
    portableData: 'Portable Data', backupTitle: 'Backup and Restore', backupCopy: 'Keep Japanese study progress portable by exporting or importing the app SQLite data.', sqliteBackup: 'SQLite Backup', moveProgress: 'Move progress between PCs', backupPanelCopy: 'Export creates a JSON file containing vocabulary, character cards, dialogues, review history, and settings. Import replaces the current SQLite database with the backup file.', exportSqlite: 'Export SQLite Data', importBackup: 'Import Backup', resetSeeds: 'Reset to Seeds',
    editWord: 'Edit Word', romaji: 'Romaji', category: 'Category', tags: 'Tags', personalHint: 'Personal Hint', exampleSentence: 'Example Sentence', exampleTranslation: 'Example Translation', cancel: 'Cancel', saveEntry: 'Save Entry',
    toastVocabularySaved: 'Vocabulary entry saved.', toastVocabularyDeleted: 'Vocabulary entry deleted.', toastCharacterAdded: 'Character card added.', toastCharacterDeleted: 'Character card deleted.', toastDialogueJson: 'Dialogue lines must be valid JSON.', toastDialogueAdded: 'Dialogue scenario added.', toastDialogueDeleted: 'Dialogue deleted.', toastSpeechUnavailable: 'Speech synthesis is not available in this browser.', toastBackupDownloaded: 'SQLite backup downloaded.', toastBackupImported: 'Backup imported.', toastSeedsRestored: 'Default SQLite data restored.', confirmDeleteWord: 'Delete {word}?', confirmDeleteCharacter: 'Delete {char}?', confirmDeleteDialogue: 'Delete {title}?', confirmResetSeeds: 'Replace all local study data with the default JSON dataset?'
  },
  de: {
    navDashboard: 'Übersicht', navVocabulary: 'Vokabeln', navFlashcards: 'Karteikarten', navCharacters: 'Zeichen', navDialogue: 'Dialog', navAdmin: 'Admin', navQuickAdd: 'Schnell hinzufügen', navBackup: 'Backup', navStart: 'Start', navDays: 'Tage', navOpen: 'Navigation öffnen', searchPlaceholder: 'Wörter, Lesungen, Bedeutungen suchen...', searchLabel: 'Lerndaten suchen', languageLabel: 'Sprache',
    loadingDatabase: 'Lokale Lerndatenbank wird geöffnet...', databaseOpenError: 'SQLite-Datenbank konnte nicht geöffnet werden', databaseWriteError: 'Prüfe, ob der Nuxt-Server in den Datenordner des Projekts schreiben kann.',
    dashEyebrow: 'Japanisch meistern', dashTitle: 'Willkommen zurück.', dashCopy: 'Ein ruhiger Lernplatz für Vokabeln, Kanji und praktische Dialoge. Karten, Hinweise, Szenarien und Fortschritt liegen in einer lokalen SQLite-Datenbank.', dashBeginReview: 'Wiederholung starten', metricVocabulary: 'Vokabeln', masteredWords: '{count} gemeisterte Wörter', metricDialogueSets: 'Dialogsets', scenarioPractice: 'Szenariobasiertes Üben', metricDailyGoal: 'Tagesziel', recentlyAdded: 'Kürzlich hinzugefügt', libraryNotes: 'Bibliotheksnotizen', viewLibrary: 'Bibliothek anzeigen', adminEyebrow: 'Verwaltung', manageCorpus: 'Lernkorpus verwalten', manageCorpusCopy: 'Vokabeln, persönliche Hinweise, Zeichenkarten, Dialogszenarien, Tags und Beispiele sind im Adminbereich bearbeitbar.', openAdmin: 'Admin öffnen', portableProgress: 'Portabler Fortschritt', exportImportTitle: 'SQLite-Daten exportieren oder importieren', exportImportCopy: 'Lade ein JSON-Backup herunter und importiere es auf einem anderen PC, um Inhalte und Verlauf mitzunehmen.', backupTools: 'Backup-Werkzeuge',
    vocabEyebrow: 'Persönliches Lexikon', vocabTitle: 'Vokabelbibliothek', vocabCopy: 'Suche, wiederhole und pflege die Wörter für Karteikarten und Dialogübungen.', addWord: 'Wort hinzufügen', noVocabularyMatches: 'Keine Vokabeln passen zur Suche.',
    flashEyebrow: 'Sitzungsfortschritt', flashTitle: 'Bedeutungsmodus', flashCopy: 'Wähle die Sitzungsgröße, tippe die englische Bedeutung und sammle Punkte mit gespeichertem Verlauf.', newSession: 'Neue Sitzung', howManyCards: 'Wie viele Karten?', cardsAvailable: '{count} Vokabelkarten sind zur Wiederholung verfügbar.', practiceFilters: 'Übungsfilter', practiceTags: 'Übungstags', allTagsSelected: 'Alle Tags enthalten', tagPoolCount: '{count} passende Wörter', selectedTagCount: '{count} Tags ausgewählt', selectTags: 'Tags auswählen', selectVocab: 'Vokabeln auswählen', selectAll: 'Alle auswählen', deselectAll: 'Alle abwählen', applySelection: 'Auswahl anwenden', selectedVocabCount: '{count} ausgewählt', cardsThisSession: 'Karten in dieser Sitzung', startFlashcards: 'Karteikarten starten', practiceHistory: 'Übeverlauf', recentSessions: 'Letzte Sitzungen', noPracticeSessions: 'Noch keine Übesitzungen.', points: 'Punkte', sessionComplete: 'Sitzung abgeschlossen', correctCount: '{correct} / {total} richtig', sessionScore: 'Dein Ergebnis war {score}%. Diese Sitzung wurde im Übeverlauf gespeichert.', reviewVocabulary: 'Vokabeln ansehen', typeMeaningHint: 'Tippe die englische Bedeutung. Groß-/Kleinschreibung ist egal.', meaning: 'Bedeutung', checkAnswer: 'Antwort prüfen', finishSession: 'Sitzung beenden', nextCard: 'Nächste Karte', context: 'Kontext', addVocabularyToBegin: 'Füge im Admin Vokabeln hinzu, um eine Wiederholung zu starten.', correct: 'Richtig', incorrect: 'Falsch', noPersonalHint: 'Noch kein persönlicher Hinweis gespeichert.',
    charEyebrow: 'Zeichenübung', charTitle: 'Kanji-Sitzung', charCopy: 'Zeichne das Zeichen nach, nutze bei Bedarf die transparente Vorlage und bestehe ab 85% Übereinstimmung.', readingMeaningHidden: 'Lesung und Bedeutung sind verborgen.', revealCharacter: 'Zeichen aufdecken', traceCharacter: 'Zeichen nachzeichnen', drawCharacterCanvas: 'Zeichen-Zeichenfläche', showHint: 'Hinweis anzeigen', hideHint: 'Hinweis ausblenden', clearDrawing: 'Löschen', checkDrawing: 'Zeichnung prüfen', continuePractice: 'Weiter', skipCharacter: 'Überspringen', drawingCorrect: 'Sehr gut!', drawingTryAgain: 'Versuch es noch einmal', drawingScore: 'Übereinstimmung: {score}%', hard: 'Schwer', good: 'Gut', easy: 'Leicht', addCharacterCards: 'Füge im Admin Zeichenkarten hinzu, um zu beginnen.', strokesInfo: '{count} Striche. {hint}',
    dialogueEyebrow: 'Dialogtrainer', dialogueTitle: 'Szenario-Übung', dialogueCopy: 'Wähle einen Dialog, lies die vorherige Nachricht und antworte mit der besten japanischen Antwort. Übersetzungen bleiben verborgen, bis du prüfst.', lines: 'Zeilen', turn: 'Runde', replyMessage: 'Auf die Nachricht antworten', listen: 'Anhören', hideHiragana: 'Hiragana ausblenden', showHiragana: 'Hiragana anzeigen', hideTranslation: 'Übersetzung ausblenden', showTranslation: 'Übersetzung anzeigen', tryThisReply: 'Versuche diese Antwort', nextTurn: 'Nächste Runde', dialogueNeedsPrompt: 'Dieser Dialog braucht eine Nicht-Lerner-Nachricht gefolgt von einer Lernerantwort.', noDialogues: 'Noch keine Dialoge.',
    manageDataTitle: 'Lerndaten verwalten', manageDataCopy: 'Verwalte Vokabeln, Hinweise, Kanjikarten, Dialogszenarien und Backups in einem Arbeitsbereich.', tabVocabulary: 'Vokabeln', tabCharacters: 'Zeichen', tabDialogues: 'Dialoge', tabBackup: 'Backup', word: 'Wort', reading: 'Lesung', hint: 'Hinweis', character: 'Zeichen', level: 'Stufe', strokes: 'Striche', addCharacter: 'Zeichen hinzufügen', delete: 'Löschen', title: 'Titel', setting: 'Ort', goal: 'Ziel', linesJson: 'Zeilen-JSON', addDialogue: 'Dialog hinzufügen',
    portableData: 'Portable Daten', backupTitle: 'Backup und Wiederherstellung', backupCopy: 'Halte deinen Japanisch-Fortschritt portabel durch Export oder Import der SQLite-Daten.', sqliteBackup: 'SQLite-Backup', moveProgress: 'Fortschritt zwischen PCs verschieben', backupPanelCopy: 'Der Export erstellt eine JSON-Datei mit Vokabeln, Zeichenkarten, Dialogen, Verlauf und Einstellungen. Der Import ersetzt die aktuelle SQLite-Datenbank.', exportSqlite: 'SQLite-Daten exportieren', importBackup: 'Backup importieren', resetSeeds: 'Auf Seed-Daten zurücksetzen',
    editWord: 'Wort bearbeiten', romaji: 'Romaji', category: 'Kategorie', tags: 'Tags', personalHint: 'Persönlicher Hinweis', exampleSentence: 'Beispielsatz', exampleTranslation: 'Beispielübersetzung', cancel: 'Abbrechen', saveEntry: 'Eintrag speichern',
    toastVocabularySaved: 'Vokabeleintrag gespeichert.', toastVocabularyDeleted: 'Vokabeleintrag gelöscht.', toastCharacterAdded: 'Zeichenkarte hinzugefügt.', toastCharacterDeleted: 'Zeichenkarte gelöscht.', toastDialogueJson: 'Dialogzeilen müssen gültiges JSON sein.', toastDialogueAdded: 'Dialogszenario hinzugefügt.', toastDialogueDeleted: 'Dialog gelöscht.', toastSpeechUnavailable: 'Sprachausgabe ist in diesem Browser nicht verfügbar.', toastBackupDownloaded: 'SQLite-Backup heruntergeladen.', toastBackupImported: 'Backup importiert.', toastSeedsRestored: 'Standard-SQLite-Daten wiederhergestellt.', confirmDeleteWord: '{word} löschen?', confirmDeleteCharacter: '{char} löschen?', confirmDeleteDialogue: '{title} löschen?', confirmResetSeeds: 'Alle lokalen Lerndaten durch den Standard-JSON-Datensatz ersetzen?'
  }
} as const

const generatedMessages: Record<LanguageCode, Record<MessageKey, string>> = {
  en: messages.en,
  de: messages.de,
  fr: {
    ...messages.en,
    navDashboard: 'Tableau de bord', navVocabulary: 'Vocabulaire', navFlashcards: 'Cartes', navCharacters: 'Caracteres', navDialogue: 'Dialogue', navAdmin: 'Admin', navQuickAdd: 'Ajout rapide', navBackup: 'Sauvegarde', navStart: 'Demarrer', navDays: 'jours', navOpen: 'Ouvrir la navigation', searchPlaceholder: 'Rechercher mots, lectures, sens...', searchLabel: 'Rechercher dans les donnees', languageLabel: 'Langue',
    loadingDatabase: 'Ouverture de la base locale...', databaseOpenError: 'Impossible d ouvrir la base SQLite', databaseWriteError: 'Verifiez que le serveur Nuxt peut ecrire dans le dossier data du projet.',
    dashEyebrow: 'Maitriser le japonais', dashTitle: 'Bon retour.', dashCopy: 'Un espace calme pour etudier le vocabulaire, les kanji et les dialogues pratiques. Cartes, indices, scenarios et progression sont stockes dans une base SQLite locale.', dashBeginReview: 'Commencer la revision', metricVocabulary: 'Vocabulaire', masteredWords: '{count} mots maitrises', metricDialogueSets: 'Dialogues', scenarioPractice: 'Pratique par scenario', metricDailyGoal: 'Objectif du jour', recentlyAdded: 'Ajoutes recemment', libraryNotes: 'Notes de bibliotheque', viewLibrary: 'Voir la bibliotheque', adminEyebrow: 'Gestion', manageCorpus: 'Gerer le corpus d etude', manageCorpusCopy: 'Vocabulaire, indices personnels, cartes de caracteres, scenarios, tags et exemples sont modifiables dans l espace admin.', openAdmin: 'Ouvrir admin', portableProgress: 'Progression portable', exportImportTitle: 'Exporter ou importer les donnees SQLite', exportImportCopy: 'Telechargez une sauvegarde JSON et importez-la sur un autre PC pour garder contenu et historique.', backupTools: 'Outils de sauvegarde',
    vocabEyebrow: 'Lexique personnel', vocabTitle: 'Bibliotheque de vocabulaire', vocabCopy: 'Recherchez, revisez et entretenez les mots qui alimentent les cartes et les dialogues.', addWord: 'Ajouter un mot', noVocabularyMatches: 'Aucun mot ne correspond a votre recherche.',
    flashEyebrow: 'Progression de session', flashTitle: 'Mode sens', flashCopy: 'Choisissez une taille de session, tapez le sens anglais et gagnez des points avec un historique sauvegarde.', newSession: 'Nouvelle session', howManyCards: 'Combien de cartes ?', cardsAvailable: '{count} cartes de vocabulaire sont disponibles.', cardsThisSession: 'Cartes dans cette session', startFlashcards: 'Demarrer les cartes', practiceHistory: 'Historique', recentSessions: 'Sessions recentes', noPracticeSessions: 'Aucune session pour le moment.', points: 'points', sessionComplete: 'Session terminee', correctCount: '{correct} / {total} correct', sessionScore: 'Votre score est {score}%. Cette session a ete enregistree.', reviewVocabulary: 'Revoir le vocabulaire', typeMeaningHint: 'Tapez le sens anglais. La casse ne compte pas.', meaning: 'Sens', checkAnswer: 'Verifier', finishSession: 'Terminer', nextCard: 'Carte suivante', context: 'Contexte', addVocabularyToBegin: 'Ajoutez du vocabulaire dans Admin pour commencer.', correct: 'Correct', incorrect: 'Incorrect', noPersonalHint: 'Aucun indice personnel enregistre.',
    charEyebrow: 'Pratique des caracteres', charTitle: 'Session kanji', charCopy: 'Revelez la lecture et le sens, puis notez votre confiance.', readingMeaningHidden: 'Lecture et sens sont caches.', revealCharacter: 'Reveler le caractere', hard: 'Difficile', good: 'Bien', easy: 'Facile', addCharacterCards: 'Ajoutez des cartes de caracteres dans Admin.', strokesInfo: '{count} traits. {hint}',
    dialogueEyebrow: 'Entraineur de dialogue', dialogueTitle: 'Pratique de scenario', dialogueCopy: 'Choisissez un dialogue, lisez le message precedent et repondez avec la meilleure replique japonaise.', lines: 'lignes', turn: 'Tour', replyMessage: 'Repondre au message', listen: 'Ecouter', hideHiragana: 'Masquer hiragana', showHiragana: 'Afficher hiragana', hideTranslation: 'Masquer traduction', showTranslation: 'Afficher traduction', tryThisReply: 'Essayez cette reponse', nextTurn: 'Tour suivant', dialogueNeedsPrompt: 'Ce dialogue a besoin d un message non-apprenant suivi d une reponse apprenant.', noDialogues: 'Aucun dialogue.',
    manageDataTitle: 'Gerer les donnees', manageDataCopy: 'Maintenez vocabulaire, indices, cartes kanji, scenarios et sauvegardes depuis un seul espace.', tabVocabulary: 'vocabulaire', tabCharacters: 'caracteres', tabDialogues: 'dialogues', tabBackup: 'sauvegarde', word: 'Mot', reading: 'Lecture', hint: 'Indice', character: 'Caractere', level: 'Niveau', strokes: 'Traits', addCharacter: 'Ajouter un caractere', delete: 'Supprimer', title: 'Titre', setting: 'Lieu', goal: 'Objectif', linesJson: 'Lignes JSON', addDialogue: 'Ajouter un dialogue',
    portableData: 'Donnees portables', backupTitle: 'Sauvegarde et restauration', backupCopy: 'Gardez votre progression portable en exportant ou important les donnees SQLite.', sqliteBackup: 'Sauvegarde SQLite', moveProgress: 'Deplacer la progression entre PC', backupPanelCopy: 'L export cree un fichier JSON avec vocabulaire, caracteres, dialogues, historique et reglages. L import remplace la base SQLite actuelle.', exportSqlite: 'Exporter SQLite', importBackup: 'Importer sauvegarde', resetSeeds: 'Reinitialiser',
    editWord: 'Modifier le mot', romaji: 'Romaji', category: 'Categorie', tags: 'Tags', personalHint: 'Indice personnel', exampleSentence: 'Phrase exemple', exampleTranslation: 'Traduction exemple', cancel: 'Annuler', saveEntry: 'Enregistrer',
    toastVocabularySaved: 'Mot enregistre.', toastVocabularyDeleted: 'Mot supprime.', toastCharacterAdded: 'Carte de caractere ajoutee.', toastCharacterDeleted: 'Carte de caractere supprimee.', toastDialogueJson: 'Les lignes doivent etre du JSON valide.', toastDialogueAdded: 'Scenario ajoute.', toastDialogueDeleted: 'Dialogue supprime.', toastSpeechUnavailable: 'Synthese vocale indisponible.', toastBackupDownloaded: 'Sauvegarde SQLite telechargee.', toastBackupImported: 'Sauvegarde importee.', toastSeedsRestored: 'Donnees par defaut restaurees.', confirmDeleteWord: 'Supprimer {word} ?', confirmDeleteCharacter: 'Supprimer {char} ?', confirmDeleteDialogue: 'Supprimer {title} ?', confirmResetSeeds: 'Remplacer toutes les donnees locales par le jeu JSON par defaut ?'
  },
  it: {
    ...messages.en,
    navDashboard: 'Cruscotto', navVocabulary: 'Vocabolario', navFlashcards: 'Flashcard', navCharacters: 'Caratteri', navDialogue: 'Dialogo', navAdmin: 'Admin', navQuickAdd: 'Aggiungi rapido', navBackup: 'Backup', navStart: 'Avvia', navDays: 'giorni', navOpen: 'Apri navigazione', searchPlaceholder: 'Cerca parole, letture, significati...', searchLabel: 'Cerca dati di studio', languageLabel: 'Lingua',
    loadingDatabase: 'Apertura database locale...', databaseOpenError: 'Impossibile aprire il database SQLite', databaseWriteError: 'Controlla che il server Nuxt possa scrivere nella cartella data.',
    dashEyebrow: 'Padroneggiare il giapponese', dashTitle: 'Bentornato.', dashCopy: 'Una scrivania tranquilla per vocabolario, kanji e dialoghi pratici. Carte, suggerimenti, scenari e progressi sono salvati in SQLite locale.', dashBeginReview: 'Inizia ripasso', metricVocabulary: 'Vocabolario', masteredWords: '{count} parole padroneggiate', metricDialogueSets: 'Set di dialoghi', scenarioPractice: 'Pratica basata su scenari', metricDailyGoal: 'Obiettivo giornaliero', recentlyAdded: 'Aggiunti di recente', libraryNotes: 'Note della libreria', viewLibrary: 'Vedi libreria', adminEyebrow: 'Amministrazione', manageCorpus: 'Gestisci il corpus', manageCorpusCopy: 'Vocabolario, suggerimenti, carte, scenari, tag ed esempi sono modificabili dall area admin.', openAdmin: 'Apri admin', portableProgress: 'Progresso portatile', exportImportTitle: 'Esporta o importa dati SQLite', exportImportCopy: 'Scarica un backup JSON e importalo su un altro PC per portare contenuti e cronologia.', backupTools: 'Strumenti backup',
    vocabEyebrow: 'Lessico personale', vocabTitle: 'Libreria vocabolario', vocabCopy: 'Cerca, ripassa e mantieni le parole per flashcard e dialoghi.', addWord: 'Aggiungi parola', noVocabularyMatches: 'Nessuna parola corrisponde alla ricerca.',
    flashEyebrow: 'Progresso sessione', flashTitle: 'Modalita significato', flashCopy: 'Scegli la dimensione, scrivi il significato inglese e accumula punti con cronologia salvata.', newSession: 'Nuova sessione', howManyCards: 'Quante carte?', cardsAvailable: '{count} carte vocabolario disponibili.', cardsThisSession: 'Carte in questa sessione', startFlashcards: 'Avvia flashcard', practiceHistory: 'Cronologia pratica', recentSessions: 'Sessioni recenti', noPracticeSessions: 'Nessuna sessione ancora.', points: 'punti', sessionComplete: 'Sessione completata', correctCount: '{correct} / {total} corrette', sessionScore: 'Il tuo punteggio e {score}%. Sessione salvata nella cronologia.', reviewVocabulary: 'Rivedi vocabolario', typeMeaningHint: 'Scrivi il significato inglese. Maiuscole ignorate.', meaning: 'Significato', checkAnswer: 'Controlla', finishSession: 'Termina sessione', nextCard: 'Carta successiva', context: 'Contesto', addVocabularyToBegin: 'Aggiungi vocaboli in Admin per iniziare.', correct: 'Corretto', incorrect: 'Errato', noPersonalHint: 'Nessun suggerimento personale salvato.',
    charEyebrow: 'Pratica caratteri', charTitle: 'Sessione kanji', charCopy: 'Mostra lettura e significato, poi valuta la tua sicurezza.', readingMeaningHidden: 'Lettura e significato sono nascosti.', revealCharacter: 'Mostra carattere', hard: 'Difficile', good: 'Bene', easy: 'Facile', addCharacterCards: 'Aggiungi carte carattere in Admin.', strokesInfo: '{count} tratti. {hint}',
    dialogueEyebrow: 'Allenatore dialoghi', dialogueTitle: 'Pratica scenario', dialogueCopy: 'Scegli un dialogo, leggi il messaggio precedente e rispondi con la miglior frase giapponese.', lines: 'righe', turn: 'Turno', replyMessage: 'Rispondi al messaggio', listen: 'Ascolta', hideHiragana: 'Nascondi hiragana', showHiragana: 'Mostra hiragana', hideTranslation: 'Nascondi traduzione', showTranslation: 'Mostra traduzione', tryThisReply: 'Prova questa risposta', nextTurn: 'Turno successivo', dialogueNeedsPrompt: 'Questo dialogo richiede un messaggio non studente seguito da una risposta studente.', noDialogues: 'Nessun dialogo.',
    manageDataTitle: 'Gestisci dati di studio', manageDataCopy: 'Gestisci vocaboli, suggerimenti, kanji, scenari e backup da un solo spazio.', tabVocabulary: 'vocabolario', tabCharacters: 'caratteri', tabDialogues: 'dialoghi', tabBackup: 'backup', word: 'Parola', reading: 'Lettura', hint: 'Suggerimento', character: 'Carattere', level: 'Livello', strokes: 'Tratti', addCharacter: 'Aggiungi carattere', delete: 'Elimina', title: 'Titolo', setting: 'Ambiente', goal: 'Obiettivo', linesJson: 'Righe JSON', addDialogue: 'Aggiungi dialogo',
    portableData: 'Dati portatili', backupTitle: 'Backup e ripristino', backupCopy: 'Mantieni portatile il progresso esportando o importando SQLite.', sqliteBackup: 'Backup SQLite', moveProgress: 'Sposta progressi tra PC', backupPanelCopy: 'L export crea un JSON con vocabolario, caratteri, dialoghi, cronologia e impostazioni. L import sostituisce il database corrente.', exportSqlite: 'Esporta SQLite', importBackup: 'Importa backup', resetSeeds: 'Ripristina dati base',
    editWord: 'Modifica parola', romaji: 'Romaji', category: 'Categoria', tags: 'Tag', personalHint: 'Suggerimento personale', exampleSentence: 'Frase esempio', exampleTranslation: 'Traduzione esempio', cancel: 'Annulla', saveEntry: 'Salva',
    toastVocabularySaved: 'Voce salvata.', toastVocabularyDeleted: 'Voce eliminata.', toastCharacterAdded: 'Carta carattere aggiunta.', toastCharacterDeleted: 'Carta carattere eliminata.', toastDialogueJson: 'Le righe devono essere JSON valido.', toastDialogueAdded: 'Scenario aggiunto.', toastDialogueDeleted: 'Dialogo eliminato.', toastSpeechUnavailable: 'Sintesi vocale non disponibile.', toastBackupDownloaded: 'Backup SQLite scaricato.', toastBackupImported: 'Backup importato.', toastSeedsRestored: 'Dati predefiniti ripristinati.', confirmDeleteWord: 'Eliminare {word}?', confirmDeleteCharacter: 'Eliminare {char}?', confirmDeleteDialogue: 'Eliminare {title}?', confirmResetSeeds: 'Sostituire tutti i dati locali con il dataset JSON predefinito?'
  },
  es: {
    ...messages.en,
    navDashboard: 'Panel', navVocabulary: 'Vocabulario', navFlashcards: 'Tarjetas', navCharacters: 'Caracteres', navDialogue: 'Dialogo', navAdmin: 'Admin', navQuickAdd: 'Agregar rapido', navBackup: 'Copia', navStart: 'Iniciar', navDays: 'dias', navOpen: 'Abrir navegacion', searchPlaceholder: 'Buscar palabras, lecturas, significados...', searchLabel: 'Buscar datos de estudio', languageLabel: 'Idioma',
    loadingDatabase: 'Abriendo base de datos local...', databaseOpenError: 'No se pudo abrir la base SQLite', databaseWriteError: 'Comprueba que el servidor Nuxt pueda escribir en la carpeta data.',
    dashEyebrow: 'Dominar japones', dashTitle: 'Bienvenido de nuevo.', dashCopy: 'Un escritorio tranquilo para vocabulario, kanji y dialogos practicos. Tarjetas, pistas, escenarios y progreso se guardan en SQLite local.', dashBeginReview: 'Comenzar repaso', metricVocabulary: 'Vocabulario', masteredWords: '{count} palabras dominadas', metricDialogueSets: 'Conjuntos de dialogo', scenarioPractice: 'Practica por escenarios', metricDailyGoal: 'Meta diaria', recentlyAdded: 'Recien agregados', libraryNotes: 'Notas de biblioteca', viewLibrary: 'Ver biblioteca', adminEyebrow: 'Administracion', manageCorpus: 'Gestionar corpus de estudio', manageCorpusCopy: 'Vocabulario, pistas, tarjetas, escenarios, etiquetas y ejemplos se editan desde Admin.', openAdmin: 'Abrir Admin', portableProgress: 'Progreso portatil', exportImportTitle: 'Exportar o importar datos SQLite', exportImportCopy: 'Descarga una copia JSON e importala en otro PC para mover contenido e historial.', backupTools: 'Herramientas de copia',
    vocabEyebrow: 'Lexico personal', vocabTitle: 'Biblioteca de vocabulario', vocabCopy: 'Busca, repasa y mantiene las palabras para tarjetas y dialogos.', addWord: 'Agregar palabra', noVocabularyMatches: 'Ninguna palabra coincide con la busqueda.',
    flashEyebrow: 'Progreso de sesion', flashTitle: 'Modo significado', flashCopy: 'Elige tamano de sesion, escribe el significado en ingles y gana puntos con historial guardado.', newSession: 'Nueva sesion', howManyCards: 'Cuantas tarjetas?', cardsAvailable: '{count} tarjetas disponibles.', cardsThisSession: 'Tarjetas en esta sesion', startFlashcards: 'Iniciar tarjetas', practiceHistory: 'Historial', recentSessions: 'Sesiones recientes', noPracticeSessions: 'Aun no hay sesiones.', points: 'puntos', sessionComplete: 'Sesion completa', correctCount: '{correct} / {total} correctas', sessionScore: 'Tu puntuacion fue {score}%. Sesion guardada en el historial.', reviewVocabulary: 'Revisar vocabulario', typeMeaningHint: 'Escribe el significado en ingles. No importa mayusculas.', meaning: 'Significado', checkAnswer: 'Comprobar', finishSession: 'Terminar sesion', nextCard: 'Siguiente tarjeta', context: 'Contexto', addVocabularyToBegin: 'Agrega vocabulario en Admin para empezar.', correct: 'Correcto', incorrect: 'Incorrecto', noPersonalHint: 'No hay pista personal guardada.',
    charEyebrow: 'Practica de caracteres', charTitle: 'Sesion kanji', charCopy: 'Revela lectura y significado, luego valora tu confianza.', readingMeaningHidden: 'Lectura y significado estan ocultos.', revealCharacter: 'Mostrar caracter', hard: 'Dificil', good: 'Bien', easy: 'Facil', addCharacterCards: 'Agrega tarjetas de caracteres en Admin.', strokesInfo: '{count} trazos. {hint}',
    dialogueEyebrow: 'Entrenador de dialogo', dialogueTitle: 'Practica de escenario', dialogueCopy: 'Elige un dialogo, lee el mensaje anterior y responde con la mejor frase japonesa.', lines: 'lineas', turn: 'Turno', replyMessage: 'Responder al mensaje', listen: 'Escuchar', hideHiragana: 'Ocultar hiragana', showHiragana: 'Mostrar hiragana', hideTranslation: 'Ocultar traduccion', showTranslation: 'Mostrar traduccion', tryThisReply: 'Prueba esta respuesta', nextTurn: 'Siguiente turno', dialogueNeedsPrompt: 'Este dialogo necesita un mensaje no aprendiz seguido de una respuesta aprendiz.', noDialogues: 'No hay dialogos.',
    manageDataTitle: 'Gestionar datos', manageDataCopy: 'Mantiene vocabulario, pistas, kanji, escenarios y copias desde un solo espacio.', tabVocabulary: 'vocabulario', tabCharacters: 'caracteres', tabDialogues: 'dialogos', tabBackup: 'copia', word: 'Palabra', reading: 'Lectura', hint: 'Pista', character: 'Caracter', level: 'Nivel', strokes: 'Trazos', addCharacter: 'Agregar caracter', delete: 'Eliminar', title: 'Titulo', setting: 'Lugar', goal: 'Objetivo', linesJson: 'Lineas JSON', addDialogue: 'Agregar dialogo',
    portableData: 'Datos portatiles', backupTitle: 'Copia y restauracion', backupCopy: 'Mantiene portatil tu progreso exportando o importando SQLite.', sqliteBackup: 'Copia SQLite', moveProgress: 'Mover progreso entre PCs', backupPanelCopy: 'La exportacion crea un JSON con vocabulario, caracteres, dialogos, historial y ajustes. La importacion reemplaza la base actual.', exportSqlite: 'Exportar SQLite', importBackup: 'Importar copia', resetSeeds: 'Restablecer datos base',
    editWord: 'Editar palabra', romaji: 'Romaji', category: 'Categoria', tags: 'Etiquetas', personalHint: 'Pista personal', exampleSentence: 'Frase de ejemplo', exampleTranslation: 'Traduccion de ejemplo', cancel: 'Cancelar', saveEntry: 'Guardar',
    toastVocabularySaved: 'Entrada guardada.', toastVocabularyDeleted: 'Entrada eliminada.', toastCharacterAdded: 'Tarjeta agregada.', toastCharacterDeleted: 'Tarjeta eliminada.', toastDialogueJson: 'Las lineas deben ser JSON valido.', toastDialogueAdded: 'Escenario agregado.', toastDialogueDeleted: 'Dialogo eliminado.', toastSpeechUnavailable: 'Sintesis de voz no disponible.', toastBackupDownloaded: 'Copia SQLite descargada.', toastBackupImported: 'Copia importada.', toastSeedsRestored: 'Datos predeterminados restaurados.', confirmDeleteWord: 'Eliminar {word}?', confirmDeleteCharacter: 'Eliminar {char}?', confirmDeleteDialogue: 'Eliminar {title}?', confirmResetSeeds: 'Reemplazar todos los datos locales con el JSON predeterminado?'
  },
  ko: {
    ...messages.en,
    navDashboard: '대시보드', navVocabulary: '어휘', navFlashcards: '플래시카드', navCharacters: '문자', navDialogue: '대화', navAdmin: '관리', navQuickAdd: '빠른 추가', navBackup: '백업', navStart: '시작', navDays: '일', navOpen: '내비게이션 열기', searchPlaceholder: '단어, 읽기, 의미 검색...', searchLabel: '학습 데이터 검색', languageLabel: '언어',
    loadingDatabase: '로컬 데이터베이스 여는 중...', databaseOpenError: 'SQLite 데이터베이스를 열 수 없습니다', databaseWriteError: 'Nuxt 서버가 프로젝트 data 폴더에 쓸 수 있는지 확인하세요.',
    dashEyebrow: '일본어 마스터하기', dashTitle: '다시 오신 것을 환영합니다.', dashCopy: '어휘, 한자, 실전 대화를 위한 조용한 학습 공간입니다. 카드, 힌트, 시나리오, 진도는 로컬 SQLite에 저장됩니다.', dashBeginReview: '복습 시작', metricVocabulary: '어휘', masteredWords: '{count}개 숙달', metricDialogueSets: '대화 세트', scenarioPractice: '상황 기반 연습', metricDailyGoal: '일일 목표', recentlyAdded: '최근 추가', libraryNotes: '라이브러리 노트', viewLibrary: '라이브러리 보기', adminEyebrow: '관리', manageCorpus: '학습 자료 관리', manageCorpusCopy: '어휘, 개인 힌트, 문자 카드, 대화 시나리오, 태그, 예문을 관리 화면에서 편집할 수 있습니다.', openAdmin: '관리 열기', portableProgress: '이동 가능한 진도', exportImportTitle: 'SQLite 데이터 내보내기 또는 가져오기', exportImportCopy: 'JSON 백업을 내려받아 다른 PC에서 가져와 콘텐츠와 기록을 옮기세요.', backupTools: '백업 도구',
    vocabEyebrow: '개인 어휘집', vocabTitle: '어휘 라이브러리', vocabCopy: '플래시카드와 대화 연습에 쓰는 단어를 검색, 복습, 관리하세요.', addWord: '단어 추가', noVocabularyMatches: '검색과 일치하는 어휘가 없습니다.',
    flashEyebrow: '세션 진행', flashTitle: '의미 모드', flashCopy: '세션 크기를 고르고 영어 의미를 입력해 점수를 얻고 기록을 저장하세요.', newSession: '새 세션', howManyCards: '몇 장을 할까요?', cardsAvailable: '{count}개의 어휘 카드를 복습할 수 있습니다.', cardsThisSession: '이번 세션 카드 수', startFlashcards: '플래시카드 시작', practiceHistory: '연습 기록', recentSessions: '최근 세션', noPracticeSessions: '아직 연습 세션이 없습니다.', points: '점', sessionComplete: '세션 완료', correctCount: '{correct} / {total} 정답', sessionScore: '점수는 {score}%입니다. 세션이 기록에 저장되었습니다.', reviewVocabulary: '어휘 복습', typeMeaningHint: '영어 의미를 입력하세요. 대소문자는 상관없습니다.', meaning: '의미', checkAnswer: '정답 확인', finishSession: '세션 종료', nextCard: '다음 카드', context: '문맥', addVocabularyToBegin: '시작하려면 관리에서 어휘를 추가하세요.', correct: '정답', incorrect: '오답', noPersonalHint: '저장된 개인 힌트가 없습니다.',
    charEyebrow: '문자 연습', charTitle: '한자 세션', charCopy: '읽기와 의미를 확인한 뒤 자신감을 평가하세요.', readingMeaningHidden: '읽기와 의미가 숨겨져 있습니다.', revealCharacter: '문자 보기', hard: '어려움', good: '좋음', easy: '쉬움', addCharacterCards: '시작하려면 관리에서 문자 카드를 추가하세요.', strokesInfo: '{count}획. {hint}',
    dialogueEyebrow: '대화 트레이너', dialogueTitle: '상황 연습', dialogueCopy: '기존 대화를 고르고 이전 메시지를 읽은 뒤 가장 좋은 일본어 답변을 고르세요.', lines: '줄', turn: '턴', replyMessage: '메시지에 답하기', listen: '듣기', hideHiragana: '히라가나 숨기기', showHiragana: '히라가나 보기', hideTranslation: '번역 숨기기', showTranslation: '번역 보기', tryThisReply: '이 답변을 보세요', nextTurn: '다음 턴', dialogueNeedsPrompt: '이 대화에는 비학습자 메시지 뒤에 학습자 답변이 필요합니다.', noDialogues: '대화가 없습니다.',
    manageDataTitle: '학습 데이터 관리', manageDataCopy: '어휘, 힌트, 한자 카드, 대화 시나리오, 백업을 한 곳에서 관리하세요.', tabVocabulary: '어휘', tabCharacters: '문자', tabDialogues: '대화', tabBackup: '백업', word: '단어', reading: '읽기', hint: '힌트', character: '문자', level: '레벨', strokes: '획수', addCharacter: '문자 추가', delete: '삭제', title: '제목', setting: '상황', goal: '목표', linesJson: '줄 JSON', addDialogue: '대화 추가',
    portableData: '이동 가능한 데이터', backupTitle: '백업 및 복원', backupCopy: 'SQLite 데이터를 내보내거나 가져와 학습 진도를 이동하세요.', sqliteBackup: 'SQLite 백업', moveProgress: 'PC 간 진도 이동', backupPanelCopy: '내보내기는 어휘, 문자 카드, 대화, 기록, 설정이 담긴 JSON을 만듭니다. 가져오기는 현재 SQLite를 대체합니다.', exportSqlite: 'SQLite 내보내기', importBackup: '백업 가져오기', resetSeeds: '기본값으로 재설정',
    editWord: '단어 편집', romaji: '로마자', category: '카테고리', tags: '태그', personalHint: '개인 힌트', exampleSentence: '예문', exampleTranslation: '예문 번역', cancel: '취소', saveEntry: '저장',
    toastVocabularySaved: '어휘가 저장되었습니다.', toastVocabularyDeleted: '어휘가 삭제되었습니다.', toastCharacterAdded: '문자 카드가 추가되었습니다.', toastCharacterDeleted: '문자 카드가 삭제되었습니다.', toastDialogueJson: '대화 줄은 올바른 JSON이어야 합니다.', toastDialogueAdded: '대화 시나리오가 추가되었습니다.', toastDialogueDeleted: '대화가 삭제되었습니다.', toastSpeechUnavailable: '이 브라우저에서는 음성 합성을 사용할 수 없습니다.', toastBackupDownloaded: 'SQLite 백업이 다운로드되었습니다.', toastBackupImported: '백업을 가져왔습니다.', toastSeedsRestored: '기본 SQLite 데이터가 복원되었습니다.', confirmDeleteWord: '{word}을(를) 삭제할까요?', confirmDeleteCharacter: '{char}을(를) 삭제할까요?', confirmDeleteDialogue: '{title}을(를) 삭제할까요?', confirmResetSeeds: '모든 로컬 학습 데이터를 기본 JSON 데이터로 바꿀까요?'
  },
  zh: {
    ...messages.en,
    navDashboard: '仪表盘', navVocabulary: '词汇', navFlashcards: '闪卡', navCharacters: '字符', navDialogue: '对话', navAdmin: '管理', navQuickAdd: '快速添加', navBackup: '备份', navStart: '开始', navDays: '天', navOpen: '打开导航', searchPlaceholder: '搜索单词、读音、含义...', searchLabel: '搜索学习数据', languageLabel: '语言',
    loadingDatabase: '正在打开本地数据库...', databaseOpenError: '无法打开 SQLite 数据库', databaseWriteError: '请检查 Nuxt 服务器是否可以写入项目 data 文件夹。',
    dashEyebrow: '掌握日语', dashTitle: '欢迎回来。', dashCopy: '用于词汇、汉字和实用对话的安静学习空间。卡片、提示、场景和进度保存在本地 SQLite 数据库中。', dashBeginReview: '开始复习', metricVocabulary: '词汇', masteredWords: '已掌握 {count} 个词', metricDialogueSets: '对话集', scenarioPractice: '基于场景的练习', metricDailyGoal: '每日目标', recentlyAdded: '最近添加', libraryNotes: '资料库笔记', viewLibrary: '查看资料库', adminEyebrow: '管理', manageCorpus: '管理学习语料', manageCorpusCopy: '词汇、个人提示、字符卡、对话场景、标签和例句都可在管理区编辑。', openAdmin: '打开管理', portableProgress: '可携带进度', exportImportTitle: '导出或导入 SQLite 数据', exportImportCopy: '下载 JSON 备份并在另一台电脑导入，以迁移内容和复习历史。', backupTools: '备份工具',
    vocabEyebrow: '个人词库', vocabTitle: '词汇库', vocabCopy: '搜索、复习和维护用于闪卡与对话练习的单词。', addWord: '添加单词', noVocabularyMatches: '没有匹配的词汇。',
    flashEyebrow: '会话进度', flashTitle: '含义模式', flashCopy: '选择会话数量，输入英文含义，并用保存的练习历史获得积分。', newSession: '新会话', howManyCards: '练习多少张？', cardsAvailable: '有 {count} 张词汇卡可复习。', cardsThisSession: '本次会话卡片数', startFlashcards: '开始闪卡', practiceHistory: '练习历史', recentSessions: '最近会话', noPracticeSessions: '还没有练习会话。', points: '分', sessionComplete: '会话完成', correctCount: '{correct} / {total} 正确', sessionScore: '你的得分是 {score}%。本次会话已保存到历史。', reviewVocabulary: '复习词汇', typeMeaningHint: '输入英文含义。大小写不敏感。', meaning: '含义', checkAnswer: '检查答案', finishSession: '完成会话', nextCard: '下一张', context: '上下文', addVocabularyToBegin: '请在管理区添加词汇以开始复习。', correct: '正确', incorrect: '错误', noPersonalHint: '还没有保存个人提示。',
    charEyebrow: '字符练习', charTitle: '汉字会话', charCopy: '显示读音和含义，然后评价你的熟悉度。', readingMeaningHidden: '读音和含义已隐藏。', revealCharacter: '显示字符', hard: '难', good: '好', easy: '简单', addCharacterCards: '请在管理区添加字符卡。', strokesInfo: '{count} 画。{hint}',
    dialogueEyebrow: '对话训练器', dialogueTitle: '情景练习', dialogueCopy: '选择一个对话，阅读上一条消息，然后选择最合适的日语回复。', lines: '行', turn: '轮次', replyMessage: '回复这条消息', listen: '收听', hideHiragana: '隐藏平假名', showHiragana: '显示平假名', hideTranslation: '隐藏翻译', showTranslation: '显示翻译', tryThisReply: '试试这个回复', nextTurn: '下一轮', dialogueNeedsPrompt: '此对话需要非学习者提示后接学习者回答。', noDialogues: '还没有对话。',
    manageDataTitle: '管理学习数据', manageDataCopy: '在一个工作区维护词汇、提示、汉字卡、对话场景和备份。', tabVocabulary: '词汇', tabCharacters: '字符', tabDialogues: '对话', tabBackup: '备份', word: '单词', reading: '读音', hint: '提示', character: '字符', level: '等级', strokes: '笔画', addCharacter: '添加字符', delete: '删除', title: '标题', setting: '场景', goal: '目标', linesJson: '行 JSON', addDialogue: '添加对话',
    portableData: '可携带数据', backupTitle: '备份与恢复', backupCopy: '通过导出或导入 SQLite 数据来迁移日语学习进度。', sqliteBackup: 'SQLite 备份', moveProgress: '在电脑之间移动进度', backupPanelCopy: '导出会创建包含词汇、字符卡、对话、复习历史和设置的 JSON 文件。导入会替换当前 SQLite 数据库。', exportSqlite: '导出 SQLite', importBackup: '导入备份', resetSeeds: '重置为默认数据',
    editWord: '编辑单词', romaji: '罗马字', category: '分类', tags: '标签', personalHint: '个人提示', exampleSentence: '例句', exampleTranslation: '例句翻译', cancel: '取消', saveEntry: '保存',
    toastVocabularySaved: '词汇已保存。', toastVocabularyDeleted: '词汇已删除。', toastCharacterAdded: '字符卡已添加。', toastCharacterDeleted: '字符卡已删除。', toastDialogueJson: '对话行必须是有效 JSON。', toastDialogueAdded: '对话场景已添加。', toastDialogueDeleted: '对话已删除。', toastSpeechUnavailable: '此浏览器不支持语音合成。', toastBackupDownloaded: 'SQLite 备份已下载。', toastBackupImported: '备份已导入。', toastSeedsRestored: '默认 SQLite 数据已恢复。', confirmDeleteWord: '删除 {word}？', confirmDeleteCharacter: '删除 {char}？', confirmDeleteDialogue: '删除 {title}？', confirmResetSeeds: '用默认 JSON 数据替换所有本地学习数据？'
  }
}

const currentLanguage = ref<LanguageCode>('en')

export const languageOptions = (Object.keys(languageNames) as LanguageCode[]).map(code => ({
  code,
  name: languageNames[code],
  flagIcon: languageFlagIcons[code]
}))

export function useUiLanguage() {
  function setLanguage(code: LanguageCode) {
    currentLanguage.value = code
    if (import.meta.client) localStorage.setItem(storageKey, code)
  }

  function t(key: string, params: Record<string, string | number> = {}) {
    const dictionary = generatedMessages[currentLanguage.value] || generatedMessages.en
    const typedKey = key as MessageKey
    const fallback = generatedMessages.en[typedKey]
    const message = dictionary[typedKey] || fallback || key
    return message.replace(/\{(\w+)\}/g, (_, param: string) => String(params[param] ?? ''))
  }

  function initLanguage() {
    if (!import.meta.client) return
    const stored = localStorage.getItem(storageKey) as LanguageCode | null
    if (stored && stored in generatedMessages) currentLanguage.value = stored
  }

  return { currentLanguage, languageOptions, setLanguage, t, initLanguage }
}